### ISSUE TITLE
Can't get attribute 'UTC'

### ISSUE THREAD

**Issue by victorcai101** [uclmr/pycodesuggest#27]
When I tried to recreate the corpus, I got the following issue:

Traceback (most recent call last):
  File "github-scraper/scraper.py", line 143, in <module>
    main(sys.argv[1:])
  File "github-scraper/scraper.py", line 130, in main
    repos = create_repos(dbFile)
  File "github-scraper/scraper.py", line 59, in create_repos
    repos = pickle.load(infile)
AttributeError: Can't get attribute 'UTC' on <module 'github3.utils' from '/Users/apple/anaconda3/lib/python3.7/site-packages/github3/utils.py'>

I zoomed  the error in:
pickle.load('/data/cloned_repos.dat')
It seems like this error is related with loading the cloned_repos.dat file.
Does anyone have the same issue?
How can I solve it?
Many thanks!

**Comment by zendevil** [comment]
I'm getting the same error. How to solve this?

**Comment by JunrQ** [comment]
Run the following code 
```shell
pip uninstall github3.py
pip install github3-py==0.9.3
```
and it works on my computer, hope to help.

**Comment by wyf18** [comment]
same error,since I use conda,there is no github3.py==0.9.3
Anybody succeeded？

**Comment by WhyK226** [comment]
> Run the following code
> 
> ```shell
> pip uninstall github3.py
> pip install github3-py==0.9.3
> ```
> 
> and it works on my computer, hope to help.

兄弟，你测试过代码，跑通了吗？如果跑通了，效果如何？

**Comment by ghost** [comment]
> > Run the following code
> > ```shell
> > pip uninstall github3.py
> > pip install github3-py==0.9.3
> > ```
> > 
> > 
> > and it works on my computer, hope to help.
> 
> 兄弟，你测试过代码，跑通了吗？如果跑通了，效果如何？

我在我的电脑上试过了，跑通了。
